// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdxtaraVWeGfK5Jf-tX23kBKn0lr1Kfm8',
    appId: '1:957513789397:web:35b32245de7e4c7ae8975c',
    messagingSenderId: '957513789397',
    projectId: 'detox-c0790',
    authDomain: 'detox-c0790.firebaseapp.com',
    storageBucket: 'detox-c0790.firebasestorage.app',
    measurementId: 'G-6F802P0NP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgYO9qPz1iGEKIoWz4wgI5Hsy3ghfIwWo',
    appId: '1:957513789397:android:ab36f4c7b4989f47e8975c',
    messagingSenderId: '957513789397',
    projectId: 'detox-c0790',
    storageBucket: 'detox-c0790.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByjrKDFa2gAQpsbc41pQtBX1mzT7RSFD8',
    appId: '1:957513789397:ios:8fa97be11b642868e8975c',
    messagingSenderId: '957513789397',
    projectId: 'detox-c0790',
    storageBucket: 'detox-c0790.firebasestorage.app',
    iosBundleId: 'com.floresr.detox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByjrKDFa2gAQpsbc41pQtBX1mzT7RSFD8',
    appId: '1:957513789397:ios:0904e066b1cb2708e8975c',
    messagingSenderId: '957513789397',
    projectId: 'detox-c0790',
    storageBucket: 'detox-c0790.firebasestorage.app',
    iosBundleId: 'com.example.detox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdxtaraVWeGfK5Jf-tX23kBKn0lr1Kfm8',
    appId: '1:957513789397:web:9d0ea142e92dbc39e8975c',
    messagingSenderId: '957513789397',
    projectId: 'detox-c0790',
    authDomain: 'detox-c0790.firebaseapp.com',
    storageBucket: 'detox-c0790.firebasestorage.app',
    measurementId: 'G-J5EY6F3LLD',
  );
}
